services:
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: fileManager-rabbitMq
#    ports:
#      - 5672:5672
#      - 15672:15672

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: FileManagerDB
    ports:
      - 5433:5432

  file-manager:
    container_name: fileManager
    build: /file-manager
    depends_on:
#      - rabbitmq
      - db
    links:
      - db
    ports:
      - 8080:8080

networks:
  main-network:
    driver: bridge