FROM maven:3.8-openjdk-17 AS build
MAINTAINER andrew
WORKDIR /fileManager
COPY . .
COPY src/main/resources/application-docker.yaml src/main/resources/application.yaml
RUN mvn package -DskipTests

FROM openjdk:17-alpine
WORKDIR /app
COPY --from=build /fileManager/target/file-manager-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "file-manager-0.0.1-SNAPSHOT.jar"]