DROP TABLE IF EXISTS Person CASCADE ;
DROP TABLE IF EXISTS folder CASCADE;
DROP TABLE IF EXISTS file CASCADE;
DROP TABLE IF EXISTS metadata CASCADE;

DROP SEQUENCE IF EXISTS person_user_id_seq;
DROP SEQUENCE IF EXISTS folder_folder_id_seq;
DROP SEQUENCE IF EXISTS metadata_metadata_id_seq;
DROP SEQUENCE IF EXISTS file_file_id_seq;